### ISSUE TITLE
What is the difference between a deep philosophical issue and a Github Issue?

### ISSUE THREAD

**Issue by rickyrombo** [bbatliner/ridj-radj-repo-for-all-your-chat-needs#3]
I'm having problems discerning deep, critical thinking problems with tasks and issues in Github related to code and repo content. Could someone explain to me what the difference is between Github issues and a forum for philosophical questions, research papers, and essentially Yahoo! answers for nerds? I'm asking for a friend.

**Comment by bbatliner** [comment]
Happy to hear you figured this out! Would you mind sharing your solution?

**Comment by rickyrombo** [comment]
This was an automated close due to lack of activity. Also, we've moved away from GitHub issues - If the issue still repros, please open a new issue on our in app feedback tracker!
